---
- name: install iptables and ipset
  become: true
  apt:
    pkg:
      - iptables
      - ipset
    state: latest
  tags:
    - blocklister

- name: check if Blocklister is already installed
  become: true
  stat:
    path: "{{ blocklisterd_install_path }}"
  register: blocklisterd_installed_check
  tags:
    - blocklister

- name: get Blocklister version
  become: true
  command: "{{ blocklisterd_install_path }} --version"
  when: blocklisterd_installed_check.stat.exists
  register: blocklisterd_installed_version
  changed_when: false
  tags:
    - blocklister

- name: check latest Blocklister version in major_version
  shell: |
    curl -s https://api.github.com/repos/dlford/blocklister/releases \
      | grep tag_name | grep {{ blocklisterd_major_version }} | grep -v rc \
      | head -1 | cut -d : -f 2,3 | tr -d "\", "
  args:
    executable: /bin/bash
  register: blocklisterd_latest_version
  changed_when: false
  tags:
    - blocklister

- name: install Blocklister
  become: true
  get_url:
    url: "https://github.com/dlford/blocklister/releases/download/{{ blocklisterd_latest_version.stdout }}/blocklister"
    dest: "{{ blocklisterd_install_path }}"
    owner: root
    group: root
    mode: "0744"
  when: blocklisterd_installed_check.stat.exists == false or blocklisterd_installed_version.stdout != blocklisterd_latest_version.stdout
  notify:
    - restart_blocklister
  tags:
    - blocklister

- name: install Blocklister config
  become: true
  copy:
    content: "{{ blocklisterd_config | to_yaml }}"
    dest: "{{ blocklisterd_config_path }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart_blocklister
  tags:
    - blocklister

- name: install Blocklister service file
  become: true
  template:
    src: "{{ role_path }}/templates/blocklister.service.j2"
    dest: /etc/systemd/system/blocklister.service
    owner: root
    group: root
    mode: "0644"
  register: blocklisterd_service_file
  notify:
    - restart_blocklister
  tags:
    - blocklister

- name: enable Blocklister service
  become: true
  systemd:
    name: blocklister.service
    daemon_reload: "{{ blocklisterd_service_file.changed }}"
    enabled: true
    state: started
  tags:
    - blocklister